apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  type: LoadBalancer
  selector:
    app: heart-disease
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
